---
# RuntimeClasses for Kata Containers
# Apply once before running helm install:
#   oc apply -f prereqs/runtimeclasses.yaml
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-cc
  labels:
    app.kubernetes.io/managed-by: kata-deploy
    kata-deploy/instance: "default"
handler: kata-qemu
overhead:
  podFixed:
    memory: "160Mi"
    cpu: "250m"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-cc-nvidia-gpu
  labels:
    app.kubernetes.io/managed-by: kata-deploy
    kata-deploy/instance: "default"
handler: kata-qemu-nvidia-gpu
overhead:
  podFixed:
    memory: "20480Mi"
    cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-cc-nvidia-gpu-tdx
  labels:
    app.kubernetes.io/managed-by: kata-deploy
    kata-deploy/instance: "default"
handler: kata-qemu-nvidia-gpu-tdx
overhead:
  podFixed:
    memory: "20480Mi"
    cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
---
kind: RuntimeClass
apiVersion: node.k8s.io/v1
metadata:
  name: kata-cc-tdx
  labels:
    app.kubernetes.io/managed-by: kata-deploy
    kata-deploy/instance: "default"
handler: kata-qemu-tdx
overhead:
  podFixed:
    memory: "2048Mi"
    cpu: "1.0"
scheduling:
  nodeSelector:
    katacontainers.io/kata-runtime: "true"
