apiVersion: apps/v1
kind: Deployment
metadata:
  name: vllm-{{ .Values.device }}
  labels:
    app: vllm
    component: vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vllm
      component: vllm
  template:
    metadata:
      labels:
        app: vllm
        component: vllm
      annotations:
        {{- if eq .Values.device "gpu" }}
        cdi.k8s.io/gpu: nvidia.com/gpu=0
        {{- end }}
        io.katacontainers.config.hypervisor.default_memory: '{{ (index .Values.deploymentConfigs .Values.device).katacontainers.memory }}'
        io.katacontainers.config.hypervisor.default_vcpus: '{{ (index .Values.deploymentConfigs .Values.device).katacontainers.vcpus }}'
        io.katacontainers.config.hypervisor.kernel_params: agent.log=debug log_buf_len=1M systemd.log_level=debug debug systemd.log_target=console systemd.journald.forward_to_console=1 console=ttyS0 debug initrd=initrd
        io.katacontainers.config.runtime.create_container_timeout: '900'
    spec:
      serviceAccountName: {{ .Values.sa }}
      restartPolicy: Always
      schedulerName: default-scheduler
      affinity: {}
      terminationGracePeriodSeconds: 120
      runtimeClassName: {{ (index .Values.deploymentConfigs .Values.device).katacontainers.runtimeClassName }}
      securityContext:
        runAsUser: 0
      initContainers:
        - name: download-model
          image: quay.io/confidential-devhub/rhaiis:latest
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              mkdir -p /models-cache/hf && \
              mkdir -p /models-cache/.cache && \
              export HF_HOME=/models-cache/hf && \
              export HF_HUB_OFFLINE=0 && \
              huggingface-cli download \
                --cache-dir /models-cache/.cache \
                --local-dir-use-symlinks False \
                --revision main \
                --local-dir /models-cache/{{ .Values.model.localDir }} \
                {{ .Values.model.repo }}
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - name: models-cache
              mountPath: /models-cache
      containers:
        - name: server
          image: 'quay.io/confidential-devhub/rhaiis:latest'
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - |
              {{- if eq .Values.device "gpu" }}
              echo '/usr/lib64' >> /etc/ld.so.conf.d/nvidia.conf && ldconfig && \
              {{- end }}
              python3 -m vllm.entrypoints.openai.api_server \
                --port=8080 \
                --model=/models-cache/{{ .Values.model.localDir }} \
                --served-model-name={{ .Values.model.servedName }} \
                --enable-auto-tool-choice \
                --tool-call-parser={{ .Values.model.toolCallParser }} \
                --trust-remote-code \
                {{- range $key, $val := (index .Values.deploymentConfigs .Values.device).model }}
                --{{ $key }}={{ $val }} \
                {{- end }}
          {{- with (index .Values.deploymentConfigs .Values.device).resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: HUGGING_FACE_HUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: huggingface-secret
                  key: token
            {{- range $key, $val := (index .Values.deploymentConfigs .Values.device).env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
            {{- end }}
          securityContext:
            privileged: true
            runAsUser: 0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 8
            periodSeconds: 100
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 24
          volumeMounts:
            - name: shm
              mountPath: /dev/shm
            - name: models-cache
              mountPath: /models-cache
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: shm
          emptyDir:
            medium: Memory
            sizeLimit: 1Gi
        - name: models-cache
          emptyDir:
            sizeLimit: 30Gi
      dnsPolicy: ClusterFirst
      {{- with (index .Values.deploymentConfigs .Values.device).katacontainers.resourceName }}
      tolerations:
        - key: {{ . }}
          effect: NoSchedule
      {{- end }}
  strategy:
    type: Recreate
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
