apiVersion: v1
kind: Service
metadata:
  labels:
    app: vllm
    component: vllm
  name: vllm
spec:
  clusterIP: None
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: http
  selector:
    app: vllm
    component: vllm
  sessionAffinity: None
  type: ClusterIP
