# Default values for confidential-computing.

# Namespace will be automatically set by Helm to {{ .Release.Namespace }}

# User-customizable configuration
device: "gpu"  # Options: ["gpu", "cpu"]
sa: "vllm-sa"

# Device-specific configuration
deploymentConfigs:
  gpu:
    katacontainers:
      resourceName: "nvidia.com/GH100_H100_PCIE"
      runtimeClassName: "kata-qemu-nvidia-gpu-tdx"
      memory: "32768"
      vcpus: "12"
      count: 1
    env:
      CUDA_VISIBLE_DEVICES: "0"
    resources:
      limits:
        cpu: "16"
        memory: "32Gi"
        nvidia.com/gpu: 1
      requests:
        cpu: "12"
        memory: "24Gi"
        nvidia.com/gpu: 1
  cpu:
    katacontainers:
      resourceName: ""
      runtimeClassName: "kata-qemu-tdx"
      memory: "32768"
      vcpus: "32"
      count: 0
    env:
      VLLM_CPU_KVCACHE_SPACE: "40"
      VLLM_RPC_TIMEOUT: "100000"
      VLLM_ALLOW_LONG_MAX_MODEL_LEN: "1"
      VLLM_ENGINE_ITERATION_TIMEOUT_S: "120"
      VLLM_CPU_SGL_KERNEL: "1"
      HF_HUB_DISABLE_XET: "1"
    resources:
      limits:
        cpu: "64"
        memory: "64Gi"
      requests:
        cpu: "32"
        memory: "32Gi"
    

# Model configuration
model:
  # repo: "RedHatAI/Llama-4-Scout-17B-16E-Instruct-quantized.w4a16"  # HuggingFace repo to download
  # localDir: "Llama-4-Scout-17B-16E-Instruct-quantized"             # Local directory name under /models-cache
  # servedName: "llama-4-scout-17b"                                  # Name exposed by vLLM API
  # toolCallParser: "llama4_pythonic"
  repo: "meta-llama/Meta-Llama-3.1-8B-Instruct"
  localDir: "Meta-Llama-3.1-8B-Instruct"
  servedName: "llama-3.1-8b-instruct"
  toolCallParser: "llama3_json"
  gpu:
    - --max-model-len=16000 #32000 for llama4
    - --gpu-memory-utilization=0.90 #0.98 for llama4
    - --enable-chunked-prefill
    - --enable_prefix_caching
    - --enforce-eager
    - --tensor-parallel-size=1
  cpu:
    - --block-size=128
    - --dtype=bfloat16
    - --max-model-len=8192
    - --distributed-executor-backend=mp
    - --max-num-batched-tokens=8192
    - --max-num-seqs=256
    - --tensor-parallel-size=1
    - --pipeline-parallel-size=1

# Secret configuration
hfToken: ""
