# Default values for confidential-computing.

# Namespace will be automatically set by Helm to {{ .Release.Namespace }}

# User-customizable configuration
device: "gpu"  # Options: ["gpu", "cpu"]
sa: "vllm-sa"

# Device-specific configuration
deploymentConfigs:
  gpu:
    image: quay.io/confidential-devhub/rhaiis:latest
    katacontainers:
      resourceName: "nvidia.com/GH100_H100_PCIE"
      runtimeClassName: "kata-cc-nvidia-gpu"
      memory: "32768"
      vcpus: "12"
      count: 1
    env:
      CUDA_VISIBLE_DEVICES: "0"
    resources:
      limits:
        cpu: "16"
        memory: "32Gi"
        nvidia.com/gpu: 1
      requests:
        cpu: "8"
        memory: "24Gi"
        nvidia.com/gpu: 1
  cpu:
    image: opea/vllm-cpu-ubi:v0.12.0-ubi9
    katacontainers:
      resourceName: ""
      runtimeClassName: "kata-cc"
      memory: "32768"
      vcpus: "32"
      count: 0
    env:
      VLLM_CPU_KVCACHE_SPACE: "40"
      VLLM_RPC_TIMEOUT: "100000"
      VLLM_ALLOW_LONG_MAX_MODEL_LEN: "1"
      VLLM_ENGINE_ITERATION_TIMEOUT_S: "120"
      VLLM_CPU_SGL_KERNEL: "1"
      HF_HUB_DISABLE_XET: "1"
    resources:
      limits:
        cpu: "64"
        memory: "64Gi"
      requests:
        cpu: "32"
        memory: "32Gi"
    

# Model configuration
model:
  repo: "RedHatAI/Llama-4-Scout-17B-16E-Instruct-quantized.w4a16"  # HuggingFace repo to download
  localDir: "Llama-4-Scout-17B-16E-Instruct-quantized"             # Local directory name under /models-cache
  servedName: "Llama-4-Scout-17B-16E-Instruct-quantized"           # Name exposed by vLLM API
  toolCallParser: "llama4_pythonic"
  gpu:
    - --max-model-len=32000
    - --gpu-memory-utilization=0.98
    - --enable-chunked-prefill
    - --enable_prefix_caching
    - --enforce-eager
    - --tensor-parallel-size=1
  cpu:
    - --block-size=128
    - --dtype=bfloat16
    - --max-model-len=8192
    - --distributed-executor-backend=mp
    - --max-num-batched-tokens=8192
    - --max-num-seqs=256
    - --tensor-parallel-size=1
    - --pipeline-parallel-size=1

# Secret configuration
hfToken: ""

# StorageClass configuration
# Create an LVM Cluster using the LVM Storage operator, then specify the name of the StorageClass here
storageClassName: lvms-vg1

# Model cache PVC configuration
modelCache:
  persistentStorage: true  # false = emptyDir (re-downloads every install)
  keepOnUninstall: true    # false = PVC deleted on helm uninstall
  storageSize: "64Gi"

# Open WebUI PVC configuration
openWebUI:
  storageSize: "2Gi"
  keepOnUninstall: false    # false = PVC deleted on helm uninstall
